//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStateDevelopment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Log
    {
        public int id { get; set; }
        public string operation_name { get; set; }
        public string page_name { get; set; }
        public string log_time { get; set; }
        public Nullable<int> user_id { get; set; }
        public string table_name { get; set; }
        public string new_details { get; set; }
        public string old_details { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
