//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStateDevelopment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowerQuestion
    {
        public int BorrowerQuestionID { get; set; }
        public string Question { get; set; }
        public string Control { get; set; }
        public string Priority { get; set; }
    }
}

