//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStateDevelopment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargesSlab
    {
        public int ChargesSlabID { get; set; }
        public string SlabName { get; set; }
        public string MinAmount { get; set; }
        public string MaxAmount { get; set; }
        public string ChargesAmount { get; set; }
    }
}
