//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStateDevelopment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestorFund
    {
        public int InvestorFundID { get; set; }
        public string InvestAmount { get; set; }
        public string IntrestRate { get; set; }
        public string InvestmentType { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> InvestorApplicationID { get; set; }
        public string InvestmentPeriod { get; set; }
    
        public virtual InvestorApplication InvestorApplication { get; set; }
    }
}
