//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStateDevelopment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestorApplicationCollection
    {
        public int InvestorAppCollectionId { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> AppID { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
