//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStateDevelopment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestorApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvestorApplication()
        {
            this.InvestorDocuments = new HashSet<InvestorDocument>();
            this.InvestorFeedbackHistories = new HashSet<InvestorFeedbackHistory>();
            this.InvestorFunds = new HashSet<InvestorFund>();
        }
    
        public int InvestorApplicationID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string CompleteAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string FullName { get; set; }
        public string WorkPhone { get; set; }
        public string Mobile { get; set; }
        public string TotalNoofApplication { get; set; }
        public string ApplicationNumber { get; set; }
        public Nullable<int> InvestorSubmittedQuestionsID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Descripation { get; set; }
        public Nullable<bool> RejectedStatus { get; set; }
        public Nullable<bool> ApprovalStatus { get; set; }
    
        public virtual InvestorSubmittedQuestion InvestorSubmittedQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestorDocument> InvestorDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestorFeedbackHistory> InvestorFeedbackHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestorFund> InvestorFunds { get; set; }
    }
}
