//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStateDevelopment.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QIGIEntities : DbContext
    {
        public QIGIEntities()
            : base("name=QIGIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity_Log> Activity_Log { get; set; }
        public virtual DbSet<AreaOfInvestmentInterest> AreaOfInvestmentInterests { get; set; }
        public virtual DbSet<AreaOfStock> AreaOfStocks { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AverageInvestment> AverageInvestments { get; set; }
        public virtual DbSet<BAppAm> BAppAms { get; set; }
        public virtual DbSet<BorrowerApplication> BorrowerApplications { get; set; }
        public virtual DbSet<BorrowerApplicationCollection> BorrowerApplicationCollections { get; set; }
        public virtual DbSet<BorrowerAsset> BorrowerAssets { get; set; }
        public virtual DbSet<BorrowerDocument> BorrowerDocuments { get; set; }
        public virtual DbSet<BorrowerQuestion> BorrowerQuestions { get; set; }
        public virtual DbSet<ChargesSlab> ChargesSlabs { get; set; }
        public virtual DbSet<CollateralType> CollateralTypes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<FinancialAdvisor> FinancialAdvisors { get; set; }
        public virtual DbSet<InvesterQuestion> InvesterQuestions { get; set; }
        public virtual DbSet<InvestorApplication> InvestorApplications { get; set; }
        public virtual DbSet<InvestorApplicationCollection> InvestorApplicationCollections { get; set; }
        public virtual DbSet<InvestorDocument> InvestorDocuments { get; set; }
        public virtual DbSet<InvestorFeedbackHistory> InvestorFeedbackHistories { get; set; }
        public virtual DbSet<InvestorFund> InvestorFunds { get; set; }
        public virtual DbSet<InvestorOptionQuestion> InvestorOptionQuestions { get; set; }
        public virtual DbSet<InvestorQualification> InvestorQualifications { get; set; }
        public virtual DbSet<InvestorQualificationApplication> InvestorQualificationApplications { get; set; }
        public virtual DbSet<InvestorSubmittedQuestion> InvestorSubmittedQuestions { get; set; }
        public virtual DbSet<ProductCharge> ProductCharges { get; set; }
        public virtual DbSet<ProductChargesType> ProductChargesTypes { get; set; }
        public virtual DbSet<ProductDocument> ProductDocuments { get; set; }
        public virtual DbSet<ProductDocumentType> ProductDocumentTypes { get; set; }
        public virtual DbSet<ProductImage> ProductImages { get; set; }
        public virtual DbSet<ProductInteresRateSlab> ProductInteresRateSlabs { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<SecurityType> SecurityTypes { get; set; }
 
        public virtual DbSet<TypesOfStock> TypesOfStocks { get; set; }
        public virtual DbSet<TypicalYield> TypicalYields { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<BorrowerSubmittedQuestion> BorrowerSubmittedQuestions { get; set; }
        public virtual DbSet<BorrowerOptionQuestion> BorrowerOptionQuestions { get; set; }
    }
}
