//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStateDevelopment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductDocuments = new HashSet<ProductDocument>();
            this.ProductImages = new HashSet<ProductImage>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ProductType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> ApprovalStatus { get; set; }
        public string ApprovedBy { get; set; }
        public string RejectedBy { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserEmail { get; set; }
        public string RateofReturn { get; set; }
        public Nullable<bool> ProductStatus { get; set; }
        public string MinimumPeriod { get; set; }
        public string MaximumPeriod { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<bool> RejectedStatus { get; set; }
        public string AreaOfStock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDocument> ProductDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual ProductType ProductType1 { get; set; }
    }
}
